<template>
  <div class="m-auto p-4 text-end bg-black bg-opacity-25 rounded-4 shadow">
    <h2 class="mb-0 text-info"><i class="bi text-light" :class="titleIcon"/> {{title}}</h2>
    <hr/>
    <h1 style="font-size: 4rem; line-height: 3rem" :class="data.Power === 0 ? 'opacity-25':''">
      <span class="text-monospace">{{ dataPowerEffect.toFixed(0) }}</span>
      <span class="text-info small"> W</span>
    </h1>
    <p class="mb-0 text-secondary">Total Hoje</p>
    <h2 class="mb-0 " style="line-height: 1.6rem;" :class="data.Today === 0 ? 'opacity-25':''">
      <span class="text-monospace">{{ data.Today.toFixed(3) }} </span>
      <span class="text-info small "> kWh</span>
    </h2>
    <hr/>
    <p class="mb-0 text-secondary">Total Mes</p>
    <h1 class="mb-0" style="line-height: 1.6rem;">
      <span class="text-monospace">{{ (data.Today * 0.14).toFixed(2) }}</span>
      <span class="text-warning"> €</span></h1>
  </div>
</template>
<script>
import gsap from "gsap";

export default {
  name: 'PowerStatus',
  props: {
    data: {type: Function},
    title: "",
    titleIcon: "",
  },
  data() {
    return {
      dataPowerEffect: 0,
    }
  },
  watch: {
    data(data) {
      gsap.to(this, {duration: 6, dataPowerEffect: Number(data.Power) || 0})
    }
  },
}
</script>
<style scoped>
@import url('https://fonts.googleapis.com/css2?family=Chivo+Mono:ital,wght@0,100..900;1,100..900&display=swap');


.text-monospace {
  font-family: "Chivo Mono", monospace;
  font-optical-sizing: auto;
  font-weight: 600;
  font-style: normal;
}

h1 {
  font-size: 2rem;
}

/* ----------------------------------------------
 * Generated by Animista on 2024-2-21 20:38:34
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation blink-1
 * ----------------------------------------
 */
@-webkit-keyframes blink-1 {
  0%,
  50%,
  100% {
    opacity: 1;
  }
  25%,
  75% {
    opacity: 0;
  }
}

@keyframes blink-1 {
  0%,
  50%,
  100% {
    opacity: 1;
  }
  25%,
  75% {
    opacity: 0;
  }
}

/* ----------------------------------------------
 * Generated by Animista on 2024-2-21 20:38:34
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation blink-1
 * ----------------------------------------
 */
@-webkit-keyframes blink-2 {
  0%,
  50%,
  100% {
    opacity: 1;
  }
  25%,
  75% {
    opacity: 0.3;
  }
}

@keyframes blink-2 {
  0%,
  50%,
  100% {
    opacity: 1;
  }
  25%,
  75% {
    opacity: 0.3;
  }
}

</style>