<template>
  <div class="m-auto cursor-pointer lucien-card" style="min-width: 17rem;" @click="$emit('show-detail')">
    <div class="lucien-card-inner text-end">
      <h2 class="mb-0 text-info"><i class="bi text-light" :class="titleIcon"/> {{title}}</h2>
      <hr style="border-color: rgba(92, 156, 255, 0.2)"/>
      <div class="d-inline-block px-3 py-1">
        <h1 style="font-size: 4rem; line-height: 3rem" :class="data.Power === 0 ? 'opacity-25' : ''">
          <span class="text-monospace status-transition" :class="statusClass">{{ dataPowerEffect.toFixed(0) }}</span>
          <span class="small status-transition" :class="statusClass ? statusClass : 'text-info'"> W</span>
        </h1>
      </div>
      <p class="mb-0 text-secondary">Total Hoje</p>
      <h2 class="mb-2 " style="line-height: 1.6rem;" :class="data.Today === 0 ? 'opacity-25':''">
        <span class="text-monospace">{{ data.Today.toFixed(3) }} </span>
        <span class="small text-info"> kWh</span>
      </h2>

      <h1 class="mb-0" style="line-height: 1.6rem;">
        <span class="text-monospace">{{ (data.Today * 0.14).toFixed(2) }}</span>
        <span class="text-warning"> €</span></h1>
    </div>
  </div>
</template>
<script>
import gsap from "gsap";

export default {
  name: 'PowerStatus',
  props: {
    data: {type: Object},
    title: "",
    titleIcon: "",
    warningThreshold: {type: Number, default: 0},
    dangerThreshold: {type: Number, default: 0},
    contractedPower: {type: Number, default: 0},
  },
  emits: ['show-detail'],
  computed: {
    statusClass() {
      if (!this.contractedPower || !this.data || !this.data.Power) return '';
      
      const usagePercent = (this.data.Power / this.contractedPower) * 100;
      
      if (this.dangerThreshold > 0 && usagePercent >= this.dangerThreshold) {
        return 'text-danger blink-1';
      } else if (this.warningThreshold > 0 && usagePercent >= this.warningThreshold) {
        return 'text-warning';
      }
      
      return '';
    }
  },
  data() {
    return {
      dataPowerEffect: 0,
    }
  },
  watch: {
    data(data) {
      gsap.to(this, {duration: 6, dataPowerEffect: Number(data.Power) || 0})
    }
  },
}
</script>
<style scoped>
.text-info {
  color: #5c9cff !important;
}



.cursor-pointer {
  cursor: pointer;
}

.hover-bright:hover {
  filter: brightness(1.2);
  transition: filter 0.3s;
}

.text-monospace {
  font-family: "Chivo Mono", monospace;
  font-optical-sizing: auto;
  font-weight: 600;
  font-style: normal;
}

.status-transition {
  transition: color 0.5s ease;
}

.text-warning-status {
  color: #ffda6a !important;
}

.text-danger-status {
  color: #dc3545 !important;
}

h1 {
  font-size: 2rem;
}

/* ----------------------------------------------
 * Generated by Animista on 2024-2-21 20:38:34
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation blink-1
 * ----------------------------------------
 */
@-webkit-keyframes blink-1 {
  0%,
  50%,
  100% {
    opacity: 1;
  }
  25%,
  75% {
    opacity: 0;
  }
}

@keyframes blink-1 {
  0%,
  50%,
  100% {
    opacity: 1;
  }
  25%,
  75% {
    opacity: 0;
  }
}

/* ----------------------------------------------
 * Generated by Animista on 2024-2-21 20:38:34
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation blink-1
 * ----------------------------------------
 */
@-webkit-keyframes blink-2 {
  0%,
  50%,
  100% {
    opacity: 1;
  }
  25%,
  75% {
    opacity: 0.3;
  }
}

@keyframes blink-2 {
  0%,
  50%,
  100% {
    opacity: 1;
  }
  25%,
  75% {
    opacity: 0.3;
  }
}

</style>